// ES lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Cita',
abbr_desc : 'Abreviatura',
acronym_desc : 'Acr&oacute;nimo',
del_desc : 'Borrado',
ins_desc : 'Inserci&oacute;n',
attribute_label_title : 'T&iacute;tulo',
attribute_label_id : 'ID',
attribute_label_class : 'Clase',
attribute_label_style : 'Estilo',
attribute_label_cite : 'Cita',
attribute_label_datetime : 'Fecha/Hora',
attribute_label_langdir : 'Direcci&oacute;n del texto',
attribute_option_ltr : 'Izquierda a derecha',
attribute_option_rtl : 'Derecha a izquierda',
attribute_label_langcode : 'Idioma',
attribute_label_tabindex : 'Orden de tabulaci&oacute;n',
attribute_label_accesskey : 'Tecla de acceso',
attribute_label_cite : 'Cita',
attribute_events_tab : 'Eventos',
attribute_attrib_tab : 'Atributos',
general_tab : 'General',
attrib_tab : 'Atributos',
events_tab : 'Eventos',
fieldset_general_tab : 'Configuraci&oacute;n general',
fieldset_attrib_tab : 'Atributos',
fieldset_events_tab : 'Eventos',
title_ins_element : 'Insertar',
title_del_element : 'Borrar',
title_acronym_element : 'Elemento acr&oacute;nimo',
title_abbr_element : 'Elemento abreviatura',
title_cite_element : 'Elemento cita',
remove : 'Eliminar',
not_set : '--no definido--',
insert_date : 'Insertar fecha/hora actual',
option_ltr : 'Izquierda a derecha',
option_rtl : 'Derecha a izquierda',
attribs_desc : 'Insertar/Editar Atributos',
attribs_title : 'Insertar/Editar Atributos'
});
