// SL lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Navedek', // Citat
abbr_desc : 'Okraj\u0161ava',
acronym_desc : 'Kratica',
del_desc : 'Brisanje',
ins_desc : 'Vstavljanje',
attribute_label_title : 'Naslov',
attribute_label_id : 'ID',
attribute_label_class : 'Razred',
attribute_label_style : 'Slog',
attribute_label_cite : 'Navedek', // Citat
attribute_label_datetime : 'Datum/\u010Cas',
attribute_label_langdir : 'Smer pisave',
attribute_option_ltr : 'Od leve proti desni',
attribute_option_rtl : 'Od desne proti levi',
attribute_label_langcode : 'Jezik',
attribute_label_tabindex : 'Zap. \u0161t.',
attribute_label_accesskey : 'Tipka dostopa',
attribute_label_cite : 'Navedki',
attribute_events_tab : 'Dogodki',
attribute_attrib_tab : 'Lastnosti',
general_tab : 'Splo\u0161no',
attrib_tab : 'Lastnosti',
events_tab : 'Dogodki',
fieldset_general_tab : 'Splo\u0161ne nastavitve',
fieldset_attrib_tab : 'Lastnosti elementa',
fieldset_events_tab : 'Dogodki elementa',
title_ins_element : 'Vstavljanje elemeta',
title_del_element : 'Brisanje elementa',
title_acronym_element : 'Kratica elementa',
title_abbr_element : 'Okraj\u0161ava elementa',
title_cite_element : 'Navedek elementa',
remove : 'Odstrani',
not_set : '--Ni nastavljeno--',
insert_date : 'Vstavi trenutni datum/\u010Das',
option_ltr : 'Od leve proti desni',
option_rtl : 'Od desne proti levi',
attribs_desc : 'Vstavi/Uredi lastnosti',
attribs_title : 'Vstavi/Uredi lastnosti'
});
