// ES lang variables

tinyMCE.addToLang('table',{
general_tab : 'General',
advanced_tab : 'Avanzado',
general_props : 'Opciones generals',
advanced_props : 'Opciones avanzadas',
desc : 'Inserta una nueva tabla',
row_before_desc : 'Inserta una fila (antes)',
row_after_desc : 'Inserta una fila (despu&eacute;s)',
delete_row_desc : 'Suprimir fila',
col_before_desc : 'Inserta una columna (antes)',
col_after_desc : 'Inserta una columna (despu&eacute;s)',
delete_col_desc : 'Suprimir columna',
rowtype : 'Tipo de fila',
title : 'Insertar/Modificar la tabla',
width : 'Ancho',
height : 'Alto',
cols : 'Columnas',
rows : 'Filas',
cellspacing : 'Espaciado de celda',
cellpadding : 'Relleno de celda',
border : 'Borde',
align : 'Alineaci&oacute;n',
align_default : 'Predeterminado',
align_left : 'Izquierda',
align_right : 'Derecha',
align_middle : 'Centrado',
row_title : 'Propiedades de la fila',
cell_title : 'Propiedades de la celda',
cell_type : 'Tipo de celda',
row_desc : 'Propiedades de la fila',
cell_desc : 'Propiedades de la celda',
valign : 'Alineaci&oacute;n vertical',
align_top : 'Arriba',
align_bottom : 'Abajo',
props_desc : 'Propiedades de la tabla',
bordercolor : 'Color del borde',
bgcolor : 'Color de fondo',
merge_cells_title : 'Vincular celdas',
split_cells_desc : 'Dividir celdas',
merge_cells_desc : 'Vincular celdas',
cut_row_desc : 'Cortar la fila',
copy_row_desc : 'Copiar la fila',
paste_row_before_desc : 'Pegar fila (antes)',
paste_row_after_desc : 'Pegar fila (despu&eacute;s)',
id : 'Id',
style: 'Estilo',
langdir : 'Direcci&oacute;n del lenguaje',
langcode : 'C&oacute;digo del lenguaje',
mime : 'Tipo MIME',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda',
bgimage : 'Imagen de fonso',
summary : 'Resumen',
td : 'Datos',
th : 'Encabezado',
cell_cell : 'Actualizar celda actual',
cell_row : 'Actualizar todas las celdas en la fila',
cell_all : 'Actualizar todas las celdas en la tabla',
row_row : 'Actualizar fila actual',
row_odd : 'Actualizar filas impares',
row_even : 'Actualizar filas pares',
row_all : 'Actualizar todas las filas',
thead : 'Encabezado de la tabla',
tbody : 'Cuerpo de la tabla',
tfoot : 'Pie de la tabla',
del : 'Eliminar tabla',
scope : 'Alcance',
row : 'Fila',
col : 'Columna',
rowgroup : 'Grupo de filas',
colgroup : 'Grupo de columnas',
col_limit : 'Ha superado el n&uacute;mero m&aacute;ximo de columnas {$cols}.',
row_limit : 'Ha superado el n&uacute;mero m&aacute;ximo de filas {$rows}.',
cell_limit : 'Ha superado el n&uacute;mero m&aacute;ximo de celdas {$cells}.',
missing_scope: ' ¿Est&aacute; seguro que desea continuar sin especificar el alcance del encabezado de celda? Sin &eacute;l podr&iacute;a ser dificultoso para algunos usuarios entender el contenido o los datos mostrados en la tabla.',
caption : 'Encabezado de la tabla'
});
