// JA lang variables
// Translator Mitsuhiro Yoshida (http://mitstek.com/)

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '詳細',
general_props : '一般プロパティ',
advanced_props : '詳細プロパティ',
desc : '新しいテーブルを挿入する',
row_before_desc : '行を前に挿入する',
row_after_desc : '行を後に挿入する',
delete_row_desc : '列を削除する',
col_before_desc : '列を前に挿入する',
col_after_desc : '列を後に挿入する',
delete_col_desc : '列を削除する',
rowtype : 'テーブルの行',
title : 'テーブルを挿入/修正する',
width : '幅',
height : '高さ',
cols : '列数',
rows : '行数',
cellspacing : 'セル余白',
cellpadding : 'セル間隔',
border : '枠線',
align : '横配置指定',
align_default : 'デフォルト',
align_left : '左',
align_right : '右',
align_middle : '中央',
row_title : 'テーブル行プロパティ',
cell_title : 'テーブルセルプロパティ',
cell_type : 'セルタイプ',
row_desc : 'テーブル行プロパティ',
cell_desc : 'テーブルセルプロパティ',
valign : '縦配置指定',
align_top : '上端',
align_bottom : '下端',
props_desc : 'テーブルプロパティ',
bordercolor : '枠線色',
bgcolor : '背景色',
merge_cells_title : 'テーブルセルを結合する',
split_cells_desc : 'テーブルの結合セルを分離する',
merge_cells_desc : 'テーブルセルを結合する',
cut_row_desc : 'テーブル行を切り取る',
copy_row_desc : 'テーブル行をコピーする',
paste_row_before_desc : 'テーブル行を前に貼り付ける',
paste_row_after_desc : 'テーブル行を後に貼り付ける',
id : 'ID',
style: 'スタイル',
langdir : '言語方向',
langcode : '言語コード',
mime : 'ターゲットMIMEタイプ',
ltr : '左から右',
rtl : '右から左',
bgimage : '背景イメージ',
summary : '要約',
td : "データ",
th : "ヘッダ",
cell_cell : '現在のセルを更新する',
cell_row : '行のすべてのセルを更新する',
cell_all : 'テーブルのすべてのセルを更新する',
row_row : '現在の行を更新する',
row_odd : '奇数の行を更新する',
row_even : '偶数の行を更新する',
row_all : 'テーブルのすべての行を更新する',
thead : 'テーブルヘッダ',
tbody : 'テーブルボディ',
tfoot : 'テーブルフッタ',
del : 'テーブルを削除する',
scope : 'スコープ',
row : '行',
col : '列',
rowgroup : '行グループ',
colgroup : '列グループ',
col_limit : 'あなたは列の最大値 {$cols} を超えました。',
row_limit : 'あなたは行の最大値 {$rows} を超えました。',
cell_limit : 'あなたはセルの最大値 {$cells} を超えました。',
missing_scope: '本当にこのテーブルヘッダセルのスコープを指定しなくてもよろしいですか? スコープなしでは、テーブルに表示されるコンテンツまたはデータを、障害を持ったユーザが理解できない可能性があります。',
caption : 'テーブル見出し'
});
