// SL lang variables

tinyMCE.addToLang('table',{
general_tab : 'Splo\u0161no',
advanced_tab : 'Napredno',
general_props : 'Splo\u0161ne lastnosti',
advanced_props : 'Napredne lastnosti',
desc : 'Vstavi novo tabelo',
row_before_desc : 'Vstavi vrstico pred',
row_after_desc : 'Vstavi vrstico po',
delete_row_desc : 'Izbri\u0161 vrstico',
col_before_desc : 'Vstavi stolpev pred',
col_after_desc : 'Vstavi stolpec po',
delete_col_desc : 'Izbri\u0161 stolpec',
rowtype : 'Vrstica v tabeli',
title : 'Vstavi/Posodobi tabelo',
width : '\u0160irina',
height : 'Vi\u0161ina',
cols : 'Stolpcev',
rows : 'Vrstic',
cellspacing : 'Razmik celic',
cellpadding : 'Podlaganje celic',
border : 'Obroba',
align : 'Poravnava',
align_default : 'Privzeto',
align_left : 'Levo',
align_right : 'Desno',
align_middle : 'Sredina',
row_title : 'Lastnosti vrstice',
cell_title : 'Lastnosti celice',
cell_type : 'Tip celice',
row_desc : 'Lastnosti vrstice',
cell_desc : 'Lastnosti celice',
valign : 'Navpi\u010Dna poravnava',
align_top : 'Vrh',
align_bottom : 'Dno',
props_desc : 'Lastnosti tabele',
bordercolor : 'Barva obrobe',
bgcolor : 'Barva ozadja',
merge_cells_title : 'Spoji celice',
split_cells_desc : 'Razdeli spojene celice',
merge_cells_desc : 'Spoji celice',
cut_row_desc : 'Izre\u017Ei vrstico',
copy_row_desc : 'Kopiraj vrstico',
paste_row_before_desc : 'Prilepi vrstico pred',
paste_row_after_desc : 'Prilepi vrstico po',
id : 'Id',
style: 'Slog',
langdir : 'Smer pisave',
langcode : 'Koda jezika',
mime : 'Ciljni MIME tip',
ltr : 'Od leve proti desni',
rtl : 'Od desne proti levi',
bgimage : 'Slika za ozadje',
summary : 'Povzetek',
td : "Podatek",
th : "Glava",
cell_cell : 'Posodobi trenutno celico',
cell_row : 'Posodobi vse celice vrstice',
cell_all : 'Posodobi vse celice tabele',
row_row : 'Posodobi trenutno vrstico',
row_odd : 'Posodobi lihe vrstice',
row_even : 'Posodobi sode vrstice',
row_all : 'Posodobi vse vrstice',
thead : 'Glava tabele',
tbody : 'Telo tabele',
tfoot : 'Noga tabele',
del : 'Delete table',
scope : 'Obseg', // Doseg
row : 'Vrstica',
col : 'Stilpec',
rowgroup : 'Skupina vrstic',
colgroup : 'Skupina stolpcev',
col_limit : 'Presegli ste dovoljeno \u0161tevilo stolpcev: {$cols}.',
row_limit : 'Presegli ste dovoljeno \u0161tevilo vrstic: {$rows}.',
cell_limit : 'Presegli ste dovoljeno \u0161tevilo celic: {$cells}.',
missing_scope: 'Ali ste prepri\u010Dani, da \u017Eelite nadaljevati ne da bi dolo\u010Dili obseg glave tabele? Brez tega je razumevanje vsebine tabele lahko ote\u017Eeno ljudem s posebnimi potrebami!',
caption : 'Opis tabele'
});
