// Trad. Chinese lang variables
// Translator Andy Chan (http://www.cite.hku.hk/)

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '進階',
general_props : '一般屬性',
advanced_props : '進階屬性',
desc : '插入一個新表格',
row_before_desc : '在之前插入一行',
row_after_desc : '在之後插入一行',
delete_row_desc : '刪除一行',
col_before_desc : '在之前插入一欄',
col_after_desc : '在之後插入一欄',
delete_col_desc : '移除一欄',
rowtype : '行在表格部份',
title : '插入/更改表格',
width : '闊度',
height : '高度',
cols : '欄',
rows : '行',
cellspacing : '單元格間距',
cellpadding : '單元格邊距',
border : '邊框',
align : '對齊',
align_default : '預設',
align_left : '左',
align_right : '右',
align_middle : '中間',
row_title : '表格行屬性',
cell_title : '表格單元格屬性',
cell_type : '單元格種類',
row_desc : '表格行屬性',
cell_desc : '表格單元格屬性',
valign : '垂直對齊',
align_top : '頂部',
align_bottom : '底部',
props_desc : '表格屬性',
bordercolor : '邊框顏色',
bgcolor : '背景顏色',
merge_cells_title : '合拼單元格',
split_cells_desc : '分離已合拼的單元格',
merge_cells_desc : '合拼單元格',
cut_row_desc : '剪下表格行',
copy_row_desc : '複製表格行',
paste_row_before_desc : '在之前貼上表格行',
paste_row_after_desc : '在之後貼上表格行',
id : 'Id',
style: 'Style',
langdir : '語言方向',
langcode : '語言碼',
mime : '目標MIME種類',
ltr : '左至右',
rtl : '右至左',
bgimage : '背景圖片',
summary : '摘要',
td : "數據",
th : "頁頭",
cell_cell : '更新這個單元格',
cell_row : '更新所有在行內的單元格',
cell_all : '更新表格內所有單元格',
row_row : '更新這個一行',
row_odd : '更新表格內所有單數的單元格',
row_even : '更新表格內所有雙數的單元格',
row_all : '更新表格內所有單元格',
thead : '表格頂部',
tbody : '表格主體',
tfoot : '表格底部',
del : '刪除表格',
scope : '範圍',
row : '行',
col : '欄',
rowgroup : '行組',
colgroup : '欄組',
col_limit : '已超過了最大可設定的欄數量： {$cols} 欄。',
row_limit : '已超過了最大可設定的行數量： {$rows} 行。',
cell_limit : '已超過了最大可設定的單元格數量 {$cells} 格。',
missing_scope: '你確定在未有指定一個表格頂部的範圍之下繼續嗎？沒有它，一些傷殘人士可能在理解表格的內容或資料時遇上困難。',
caption : '表格標題'
});
