// ES lang variables

tinyMCE.addToLang('style',{
title : 'Editar Estilo CSS',
styleinfo_desc : 'Editar Estilo CSS',
apply : 'Aplicar',
text_tab : 'Texto',
background_tab : 'Fondo',
block_tab : 'Bloque',
box_tab : 'Caja',
border_tab : 'Borde',
list_tab : 'Lista',
positioning_tab : 'Posici&oacute;n',
text_props : 'Texto',
text_font : 'Fuente',
text_size : 'Tama&ntilde;o',
text_weight : 'Peso',
text_style : 'Estilo',
text_variant : 'Variante',
text_lineheight : 'Ancho de la fila',
text_case : 'Min&uacute;s./May&uacute;s.',
text_color : 'Color',
text_decoration : 'Decorativos',
text_overline : 'Subrayado superior',
text_underline : 'Subrayado',
text_striketrough : 'Tachado',
text_blink : 'Parpadeo',
text_none : 'Ninguno',
background_color : 'Color de fondo',
background_image : 'Imagen de fondo',
background_repeat : 'Repetici&oacute;n',
background_attachment : 'Adjunto',
background_hpos : 'Posici&oacute;n horizontal',
background_vpos : 'Posici&oacute;n vertical',
block_wordspacing : 'Espacio entre letras',
block_letterspacing : 'Espacio entre l&iacute;neas',
block_vertical_alignment : 'Alineaci&oacute;n vertical',
block_text_align : 'Alineaci&oacute;n del texto',
block_text_indent : 'Sangr&iacute;a',
block_whitespace : 'Espacio en blanco',
block_display : 'Visualizaci&oacute;n',
box_width : 'Ancho',
box_height : 'Alto',
box_float : 'Flotar',
box_clear : 'Limpiar',
padding : 'Relleno',
same : 'Lo mismo en todos',
top : 'Arriba',
right : 'Derecha',
bottom : 'Abajo',
left : 'Izquierda',
margin : 'Margen',
style : 'Estilo',
width : 'Ancho',
height : 'Alto',
color : 'Color',
list_type : 'Tipo',
bullet_image : 'Imagen de la vi&ntilde;eta',
position : 'Posici&oacute;n',
positioning_type : 'Tipo',
visibility : 'Visibilidad',
zindex : 'Z-index',
overflow : 'Desbordamiento',
placement : 'Situaci&oacute;n',
clip : 'Fragmento'
});
