// ES lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Estilos',
theme_code_desc : 'Editar c&oacute;digo HTML',
theme_code_title : 'Editor de c&oacute;digo HTML',
theme_code_wordwrap : 'Ajustar al margen',
theme_sub_desc : 'Sub&iacute;ndice',
theme_sup_desc : 'Super&iacute;ndice',
theme_hr_desc : 'Insertar regla horizontal',
theme_removeformat_desc : 'Limpiar formato',
theme_custom1_desc : 'Su descripci&oacute;n personal aqu&iacute;',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensi&oacute;n',
insert_image_vspace : 'Espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineaci&oacute;n',
insert_image_align_default : 'Por defecto',
insert_image_align_baseline : 'L&iacute;nea base',
insert_image_align_top : 'Arriba',
insert_image_align_middle : 'Medio',
insert_image_align_bottom : 'Debajo',
insert_image_align_texttop : 'Texto arriba',
insert_image_align_absmiddle : 'Centrado horitzontal',
insert_image_align_absbottom : 'Centrado abajo',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'Derecha',
theme_font_size : '-- Tama&ntilde;o --',
theme_fontdefault : '-- Fuente --',
theme_block : '-- Formato --',
theme_paragraph : 'P&aacute;rrafo',
theme_div : 'Div',
theme_address : 'Direcci&oacute;n',
theme_pre : 'Preformateado',
theme_h1 : 'Encabezado 1',
theme_h2 : 'Encabezado 2',
theme_h3 : 'Encabezado 3',
theme_h4 : 'Encabezado 4',
theme_h5 : 'Encabezado 5',
theme_h6 : 'Encabezado 6',
theme_colorpicker_title : 'Seleccionar color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Seleccionar color del texto',
theme_backcolor_desc : 'Seleccionar color de fondo',
theme_charmap_title : 'Seleccionar car&aacute;cter personalizado',
theme_charmap_desc : 'Insertar caracteres personalizados',
theme_visualaid_desc : 'Mostrar/ocultar l&iacute;nea de gu&iacute;a/elementos invisibles',
insert_anchor_title : 'Insertar/editar ancla',
insert_anchor_name : 'Nombre del ancla',
theme_anchor_desc : 'Insertar/editar ancla',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'Copiar, retallar i enganxar no &eacute;s possible amb Mozilla i Firefox.\nVols m&eacute;s informaci&oacute; sobre aquesta q&euml;esti&oacute;?',
theme_path : 'Ruta',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Pegar',
link_list : 'Lista de hiperv&iacute;nculos',
image_list : 'Lista de im&aacute;genes',
browse : 'Examinar',
image_props_desc : 'Propiedades de la imagen',
newdocument_desc : 'Nuevo documento',
class_name : 'Clase',
newdocument : '¿Est&aacute; seguro que desea limpiar todo el contenido?',
about_title : 'Acerca de TinyMCE',
about : 'Acerca de ',
license : 'Licencia',
plugins : 'Complementos',
plugin : 'Complemento',
author : 'Autor',
version : 'Versi&oacute;n',
loaded_plugins : 'Complementos cargados',
help : 'Ayuda',
not_set : '-- Ninguno --',
close : 'Cerrar',
toolbar_focus : 'Ir a los botones de herramientas - Alt+Q, Ir al editor - Alt-Z, Ir a la ruta del elemento - Alt-X',
invalid_data : 'Error: los valores introducidos son incorrectos, se muestran en rojo.',
more_colors : 'M&aacute;s colores',
color_picker_tab : 'Selector',
color_picker : 'Selector de color',
web_colors_tab : 'Paleta',
web_colors : 'Paleta de colores',
named_colors_tab : 'Nombres',
named_colors : 'Nombres de colores',
color : 'Color:',
color_name : 'Nombre:',
is_email : 'La URL introducida parace ser una direcci&oacute;n de correo, ¿desea a&ntilde;adir el prefijo mailto?',
is_external : 'La URL parece ser un hiperv&iacute;nculo externo, ¿desea a&ntilde;adir el prefijo http://?'

});
