// JA lang variables
// Translator Mitsuhiro Yoshida (http://mitstek.com/)

tinyMCE.addToLang('',{
theme_style_select : '-- スタイル --',
theme_code_desc : 'HTMLソースを編集する',
theme_code_title : 'HTMLソースエディタ',
theme_code_wordwrap : 'ワードラップ',
theme_sub_desc : '下付き',
theme_sup_desc : '上付き',
theme_hr_desc : '水平ルーラを挿入する',
theme_removeformat_desc : '書式設定を削除する',
theme_custom1_desc : 'Your custom description here',
insert_image_border : '枠線',
insert_image_dimensions : 'サイズ',
insert_image_vspace : '垂直方向のスペース',
insert_image_hspace : '水平方向のスペース',
insert_image_align : '配置',
insert_image_align_default : '-- 設定なし --',
insert_image_align_baseline : 'ベースライン揃え',
insert_image_align_top : '上揃え',
insert_image_align_middle : '中央揃え',
insert_image_align_bottom : '下揃え',
insert_image_align_texttop : 'テキスト上揃え',
insert_image_align_absmiddle : '中央揃え (絶対指定)',
insert_image_align_absbottom : '下揃え (絶対指定)',
insert_image_align_left : '左',
insert_image_align_right : '右',
theme_font_size : '-- フォントサイズ --',
theme_fontdefault : '-- フォントファミリー --',
theme_block : '-- フォーマット --',
theme_paragraph : '段落',
theme_div : 'ブロック要素',
theme_address : 'アドレス',
theme_pre : 'フォーマット済み',
theme_h1 : '見出し 1',
theme_h2 : '見出し 2',
theme_h3 : '見出し 3',
theme_h4 : '見出し 4',
theme_h5 : '見出し 5',
theme_h6 : '見出し 6',
theme_blockquote : '引用',
theme_code : 'コード',
theme_samp : 'コードサンプル',
theme_dt : '定義語 ',
theme_dd : '定義の説明',
theme_colorpicker_title : '色を選択する',
theme_colorpicker_apply : '適用',
theme_forecolor_desc : '文字色を選択する',
theme_backcolor_desc : '背景色を選択する',
theme_charmap_title : '特殊文字を選択する',
theme_charmap_desc : '特殊文字を挿入する',
theme_visualaid_desc : 'ガイドライン/非表示要素を切り替える',
insert_anchor_title : 'アンカーを挿入/編集する',
insert_anchor_name : 'アンカー名',
theme_anchor_desc : 'アンカーを挿入/編集する',
theme_insert_link_titlefield : 'タイトル',
theme_clipboard_msg : 'MozillaおよびFirefoxでは、コピー/切り取り/貼り付けを使用することはできません。\nこの問題に関する詳細情報が必要ですか?',
theme_path : 'パス',
cut_desc : '切り取り',
copy_desc : 'コピー',
paste_desc : '貼り付け',
link_list : 'リンクリスト',
image_list : 'イメージリスト',
browse : '閲覧',
image_props_desc : 'イメージプロパティ',
newdocument_desc : '新しいドキュメント',
class_name : 'クラス',
newdocument : '本当にすべてのコンテンツをクリアしてもよろしいですか?',
about_title : 'About TinyMCE',
about : 'About',
license : 'ライセンス',
plugins : 'プラグイン',
plugin : 'プラグイン',
author : '著者',
version : 'バージョン',
loaded_plugins : '読込み済みプラグイン',
help : 'ヘルプ',
not_set : '-- 未設定 --',
close : '閉じる',
toolbar_focus : 'ツールボタンにジャンプする - Alt+Q、エディタにジャンプする - Alt-Z、要素パスにジャンプする - Alt-X',
invalid_data : 'エラー: 無効な値が入力されました。無効な値は、赤色にマークされています。',
more_colors : 'その他の色',
color_picker_tab : 'ピッカー',
color_picker : 'カラーピッカー',
web_colors_tab : 'パレット',
web_colors : 'パレット色',
named_colors_tab : '名前付き',
named_colors : '名前付きカラー',
color : '色:',
color_name : '色名:',
is_email : 'あなたが入力したURIはメールアドレスのようです。必要な「mailto:」接頭辞を追加しますか?',
is_external : 'あなたが入力したURIは外部リンクのようです。必要な「http://」接頭辞を追加しますか?'
});
