// SL lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Slog --',
theme_code_desc : 'Uredi HTML vir',
theme_code_title : 'Urejevalnik HTML virov',
theme_code_wordwrap : 'Ovijanje besedila',
theme_sub_desc : 'Podpisano',
theme_sup_desc : 'Nadpisano',
theme_hr_desc : 'Vstavi vodoravno \u010Drto',
theme_removeformat_desc : 'Odstrani oblikovanje',
theme_custom1_desc : 'Tukaj dodajte lasten opis',
insert_image_border : 'Rob',
insert_image_dimensions : 'Dimenzije',
insert_image_vspace : 'Navpi\u010Dni razmik',
insert_image_hspace : 'Vodoravni razmik',
insert_image_align : 'Poravnava',
insert_image_align_default : '-- Ni nastavljeno --',
insert_image_align_baseline : 'Na osnovnico',
insert_image_align_top : 'Na vrh',
insert_image_align_middle : 'Na sredino',
insert_image_align_bottom : 'Na dno',
insert_image_align_texttop : 'Na vrh besedila',
insert_image_align_absmiddle : 'Na absolutno sredino',
insert_image_align_absbottom : 'Na absolutno dno',
insert_image_align_left : 'Na levo',
insert_image_align_right : 'Na desno',
theme_font_size : '-- Velikost pisave --',
theme_fontdefault : '-- Pisava --',
theme_block : '-- Oblikovanje --',
theme_paragraph : 'Odstavek',
theme_div : 'Blok',
theme_address : 'Naslov',
theme_pre : 'Predoblikovano',
theme_h1 : 'Naslov 1',
theme_h2 : 'Naslov 2',
theme_h3 : 'Naslov 3',
theme_h4 : 'Naslov 4',
theme_h5 : 'Naslov 5',
theme_h6 : 'Naslov 6',
theme_blockquote : 'Navedek',
theme_code : 'Izvorna koda',
theme_samp : 'Primer',
theme_dt : 'Definicija - pojem',
theme_dd : 'Definicija - opis',
theme_colorpicker_title : 'Izberite barvo',
theme_colorpicker_apply : 'Uporabi',
theme_forecolor_desc : 'Izberite barvo besedila',
theme_backcolor_desc : 'Izberite barvo ozadja',
theme_charmap_title : 'Izberite lasten znak',
theme_charmap_desc : 'Vstavite lasten znak',
theme_visualaid_desc : 'Preklopi vodilne \u010Drte/nevidne elemente',
insert_anchor_title : 'Vstavi/uredi sidro',
insert_anchor_name : 'Ime sidra',
theme_anchor_desc : 'Vstavi/uredi sidro',
theme_insert_link_titlefield : 'Naslov',
theme_clipboard_msg : 'Kopiraj/Izre\u017Ei/Prilepi v Mozilli in Firefoxu ni na voljo.\n\u017Delite ve\u010D informacij o tej te\u017Eavi?',
theme_path : 'Pot',
cut_desc : 'Izre\u017Ei',
copy_desc : 'Kopiraj',
paste_desc : 'Prilepi',
link_list : 'Seznam povezav',
image_list : 'Seznam slik',
browse : 'Brskaj', // Prebrskaj
image_props_desc : 'Lastnosti slike',
newdocument_desc : 'Nov dokument',
class_name : 'Razred',
newdocument : 'Ali zares \u017Eelite po\u010Distiti vso vsebino?',
about_title : 'TinyMCE vizitka',
about : 'Vizitka',
license : 'Licenca',
plugins : 'Vti\u010Dniki',
plugin : 'Vti\u010Dnik',
author : 'Avtor',
version : 'Razli\u010Dica',
loaded_plugins : 'Nalo\u017Eeni vti\u010Dniki',
help : 'Pomo\u010D',
not_set : '-- Ni nastavljeno --',
close : 'Zapri',
toolbar_focus : 'Preskok na orodjarno - Alt+Q, Preskok v urejevalnik - Alt+Z, Preskok na pot elementa - Alt+X',
invalid_data : 'Napaka: Vne\u0161ene so bile neveljavne vrednosti, ki so ozna\u010Dene z rde\u010Do.',
more_colors : 'Ve\u010D barv',
color_picker_tab : 'Po meri',
color_picker : 'Izberi barvo',
web_colors_tab : 'Paleta',
web_colors : 'Paleta barv',
named_colors_tab : 'Imenovane',
named_colors : 'Imenovane barve',
color : 'Barva:',
color_name : 'Ime:',
is_email : 'Izgleda, da ste vnesli epo\u0161tni naslov. Ali \u017Eelite dodati obvezno mailto: predpono?',
is_external : 'Izgleda, da ste vnesli zunanjo spletno povezavo. Ali \u017Eelite dodati obvezno http:// predpono?'
});
