// Trad. Chinese lang variables
// Translator Andy Chan (http://www.cite.hku.hk/)

tinyMCE.addToLang('',{
theme_style_select : '-- 風格 --',
theme_code_desc : '編輯HTML源代碼',
theme_code_title : 'HTML源代碼編輯器',
theme_code_wordwrap : '自動換行',
theme_sub_desc : '下標',
theme_sup_desc : '上標',
theme_hr_desc : '插入水平線',
theme_removeformat_desc : '移除格式',
theme_custom1_desc : '這裡是你的自訂描述',
insert_image_border : '邊框',
insert_image_dimensions : '大小',
insert_image_vspace : '垂直空位',
insert_image_hspace : '水平空位',
insert_image_align : '對齊',
insert_image_align_default : '-- 未設置 --',
insert_image_align_baseline : '底線',
insert_image_align_top : '頂部',
insert_image_align_middle : '中間',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字頂部',
insert_image_align_absmiddle : '絕對中間',
insert_image_align_absbottom : '絕對底部',
insert_image_align_left : '左',
insert_image_align_right : '右',
theme_font_size : '-- 文字大小 --',
theme_fontdefault : '-- 字體 --',
theme_block : '-- 格式 --',
theme_paragraph : '段落',
theme_div : '分段',
theme_address : '地址',
theme_pre : '預格式化',
theme_h1 : '標題 1',
theme_h2 : '標題 2',
theme_h3 : '標題 3',
theme_h4 : '標題 4',
theme_h5 : '標題 5',
theme_h6 : '標題 6',
theme_blockquote : '區塊引用',
theme_code : '代碼',
theme_samp : '代碼範例',
theme_dt : '定義項目 ',
theme_dd : '定義描述',
theme_colorpicker_title : '選擇一種顏色',
theme_colorpicker_apply : '套用',
theme_forecolor_desc : '選擇文字顏色',
theme_backcolor_desc : '選擇背景顏色',
theme_charmap_title : '選擇自訂字母',
theme_charmap_desc : '插入自訂字母',
theme_visualaid_desc : '切換指引/隱藏的原素',
insert_anchor_title : '插入/編輯錨點',
insert_anchor_name : '錨點名稱',
theme_anchor_desc : '插入/編輯錨點',
theme_insert_link_titlefield : '標題',
theme_clipboard_msg : '複製/剪下/貼上功能在Mozilla和Firefox中不能使用.\n你想知更多這問題的相關資料嗎?',
theme_path : '路徑',
cut_desc : '剪下',
copy_desc : '複製',
paste_desc : '貼上',
link_list : '連結列表',
image_list : '圖片列表',
browse : '瀏覽',
image_props_desc : '圖片屬性',
newdocument_desc : '新文件',
class_name : '類別',
newdocument : '你確定你要清除所有內容嗎？',
about_title : '關於TinyMCE',
about : '關於',
license : '許可',
plugins : '插件',
plugin : '插件',
author : '作者',
version : '版本',
loaded_plugins : '已載入插件',
help : '幫助',
not_set : '-- 未設置 --',
close : '關閉',
toolbar_focus : '跳到工具按鈕 - Alt+Q, 跳到編輯器 - Alt-Z, 跳到元件路徑 - Alt-X',
invalid_data : '錯誤: 輸入了不正確的數值，這些數值已被顯示為紅色',
more_colors : '更多顏色',
color_picker_tab : '選擇器',
color_picker : '顏色選擇器',
web_colors_tab : '調色板',
web_colors : '調色板顏色',
named_colors_tab : '已命名',
named_colors : '已命名的顏色',
color : '顏色:',
color_name : '名稱:',
is_email : '你輸入的網址似乎是一個電郵地址，你想加mailto:字首在前面嗎？',
is_external : '你輸入的網址似乎是一個外部連結, 你想加http://字首在前面嗎？'
});
