// ES lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Propiedades del documento',
	desc : 'Propiedades del documento',
	meta_tab : 'General',
	appearance_tab : 'Apariencia',
	advanced_tab : 'Avanzado',
	meta_props : 'Informaci&oacute;n Meta',
	langprops : 'Lenguaje y codificaci&oacute;n',
	meta_title : 'T&iacute;tulo',
	meta_keywords : 'Palabras clave',
	meta_description : 'Descripci&oacute;n',
	meta_robots : 'Robots',
	doctypes : 'Tipo de doc.',
	langcode : 'C&oacute;digo del lenguaje',
	langdir : 'Direcci&oacute;n del lenguaje',
	ltr : 'Izquierda a derecha',
	rtl : 'Derecha a izquierda',
	xml_pi : 'Declaraci&oacute;n XML',
	encoding : 'Codificaci&oacute;n de caracteres',
	appearance_bgprops : 'Propiedades del fondo',
	appearance_marginprops : 'M&aacute;rgenes',
	appearance_linkprops : 'Colores del v&iacute;nculo',
	appearance_textprops : 'Propiedades de texto',
	bgcolor : 'Color de fondo',
	bgimage : 'Imagen de fondo',
	left_margin : 'Margen izquierdo',
	right_margin : 'Margen derecho',
	top_margin : 'Margen superior',
	bottom_margin : 'Margen inferior',
	text_color : 'Color del texto',
	font_size : 'Tama&ntilde;o de fuente',
	font_face : 'Fuente',
	link_color : 'Color de v&iacute;nculo',
	hover_color : 'Color al pasar el rat&oacute;n por encima',
	visited_color : 'Color de v&iacute;nculo visitado',
	active_color : 'Color de de v&iacute;nculo activo',
	textcolor : 'Color',
	fontsize : 'Tama&ntilde;o de fuente',
	fontface : 'Fuente',
	meta_index_follow : 'Indexar y seguir los v&iacute;nculos',
	meta_index_nofollow : 'Indexar y no seguir los v&iacute;nculos',
	meta_noindex_follow : 'No indexar pero seguir los v&iacute;nculos',
	meta_noindex_nofollow : 'No indexar y no seguir los v&iacute;nculos',
	appearance_style : 'Propiedades de hoja de estilos y estilo',
	stylesheet : 'Hoja de estilo',
	style : 'Estilo',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'Agregar nuevo elemento',
	remove : 'Eliminar elemento seleccionado',
	moveup : 'Mover elemento seleccionado hacia arriba',
	movedown : 'Mover elemento seleccionado hacia abajo',
	head_elements : 'Elemento Head',
	info : 'Informaci&oacute;n',
	info_text : '',
	add_title : 'Elemento Title',
	add_meta : 'Elemento Meta',
	add_script : 'Elemento Script',
	add_style : 'Elemento Style',
	add_link : 'Elemento Link',
	add_base : 'Elemento Base',
	add_comment : 'Nodo Comment',
	title_element : 'Elemento Title',
	script_element : 'Elemento Script',
	style_element : 'Elemento Style',
	base_element : 'Elemento Base',
	link_element : 'Elemento Link',
	meta_element : 'Elemento Meta',
	comment_element : 'Comentario',
	src : 'Src',
	language : 'Lenguaje',
	href : 'Href',
	target : 'Target',
	rel : 'Rel',
	type : 'Tipo',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Medio',
	properties : 'Propiedades',
	name : 'Nombre',
	value : 'Valor',
	content : 'Contenido',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'General',
	advanced_props : 'Avanzado',
	delta_width : 0,
	delta_height : 0
});
