// SL lang variables

tinyMCE.addToLang('fullpage',{
	title : 'Lastnosti dokumenta',
	desc : 'Lastnosti dokumenta',
	meta_tab : 'Splo\u0161no',
	appearance_tab : 'Izgled',
	advanced_tab : 'Napredno',
	meta_props : 'Meta podatki',
	langprops : 'Jezik in kodiranje',
	meta_title : 'Naslov',
	meta_keywords : 'Klju\u010Dne besede',
	meta_description : 'Opis',
	meta_robots : 'Roboti',
	doctypes : 'Doctype',
	langcode : 'Koda jezika',
	langdir : 'Smer pisave',
	ltr : 'Od leve proti desni',
	rtl : 'Od desne proti levi',
	xml_pi : 'Najava XML',
	encoding : 'Kodiranje znakov',
	appearance_bgprops : 'Lastnosti ozadja',
	appearance_marginprops : 'Robovi telesa',
	appearance_linkprops : 'Barve povezav',
	appearance_textprops : 'Lastnosti besedila',
	bgcolor : 'Barva ozadja',
	bgimage : 'Slika za ozadje',
	left_margin : 'Levi rob',
	right_margin : 'Desni rob',
	top_margin : 'Zgornji rob',
	bottom_margin : 'Spodnji rob',
	text_color : 'Barva pisave',
	font_size : 'Velikost pisave',
	font_face : 'Vrsta pisave',
	link_color : 'Barva povezave',
	hover_color : 'Barva nakazane povezave',
	visited_color : 'Barva obiskane povezave',
	active_color : 'Barva dejavne povezave',
	textcolor : 'Barva',
	fontsize : 'Velikost pisave',
	fontface : 'Dru\u017Eina pisave',
	meta_index_follow : 'Indeksiraj in sledi povezavam',
	meta_index_nofollow : 'Indeksiraj, a ne sledi povezavam',
	meta_noindex_follow : 'Ne indeksiraj, a sledi povezavam',
	meta_noindex_nofollow : 'Ne indeksiraj in ne sledi povezavam',
	appearance_style : 'Stilna predloga in lastnosti slogov',
	stylesheet : 'Stilna predloga',
	style : 'Slog',
	author : 'Avtor',
	copyright : 'Avtorske pravice',
	add : 'Dodaj element',
	remove : 'Odstrani izbrani element',
	moveup : 'Premakni izbrani element navzgor',
	movedown : 'Premakni izbrani element navzdol',
	head_elements : 'Elementi glave',
	info : 'Informacija',
	info_text : '',
	add_title : 'Element Naslov',
	add_meta : 'Element Meta',
	add_script : 'Element Script',
	add_style : 'Element Slog',
	add_link : 'Element Povezava',
	add_base : 'Element Baza',
	add_comment : 'Komentar',
	title_element : 'Element Naslov',
	script_element : 'Element Script',
	style_element : 'Element Slog',
	base_element : 'Element Baza',
	link_element : 'Element Povezava',
	meta_element : 'Meta element',
	comment_element : 'Komentar',
	src : 'Vir',
	language : 'Jezik',
	href : 'Href',
	target : 'Cilj',
	rel : 'Rel',
	type : 'Tip',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Media',
	properties : 'Lastnosti',
	name : 'Ime',
	value : 'Vrednost',
	content : 'Vsebina',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Splo\u0161no',
	advanced_props : 'Napredno',
	delta_width : 0,
	delta_height : 0
});
