// ES lang variables
tinyMCE.addToLang('advlink',{
general_tab : 'General',
popup_tab : 'Ventana emergente',
events_tab : 'Eventos',
advanced_tab : 'Avanzado',
general_props : 'Propiedades generales',
popup_props : 'Propiedades de ventanas emergentes',
event_props : 'Eventos',
advanced_props : 'Propiedades avanzadas',
popup_opts : 'Opciones',
anchor_names : 'Anclas',
target_same : 'Abrir en esta ventana / marco',
target_parent : 'Abrir en ventana padre / marco',
target_top : 'Abrir en el marco superior (reemplaza todos los marcos)',
target_blank : 'Abrir en ventana nueva',
popup : 'Javascript popup',
popup_url : 'URL de la ventana emergenteL',
popup_name : 'Nombre de la ventana',
popup_return : 'Insertar \'return false\'',
popup_scrollbars : 'Mostrar barras de desplazamiento',
popup_statusbar : 'Mostrar barra de estado',
popup_toolbar : 'Mostrar barra de herramientas',
popup_menubar : 'Mostrar barra de men&uacute;',
popup_location : 'Mostrar barra de localizaci&oacute;n',
popup_resizable : 'Permitir cambiar el tama&ntilde;o de la ventana',
popup_dependent : 'Dependientes (s&oacute;lo Mozilla/Firefox)',
popup_size : 'Tama&ntilde;o',
popup_position : 'Posici&oacute;n (X/Y)',
id : 'Id',
style: 'Estilo',
classes : 'Clases',
target_name : 'Nombre del Target',
langdir : 'Direcci&oacute;n del lenguaje',
target_langcode : 'Lenguaje del Target',
langcode : 'C&oacute;digo del lenguaje',
encoding : 'Codificaci&oacute;n de caracteres del Target',
mime : 'Tipo MIME del Target',
rel : 'Relaci&oacute;n p&aacute;gina a target',
rev : 'Relaci&oacute;n target a p&aacute;gina',
tabindex : '&Iacute;ndice de tabulaci&oacute;n',
accesskey : 'Tecla de acceso',
ltr : 'Izquierda a derecha',
rtl : 'Derecha a izquierda'
});
