// SL lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Splo\u0161no',
popup_tab : 'Pojavno okno',
events_tab : 'Dogodki',
advanced_tab : 'Napredno',
general_props : 'Splo\u0161ne lastnosti',
popup_props : 'Lastnosti pojavnega okna',
event_props : 'Dogodki',
advanced_props : 'Napredne lastnosti"',
popup_opts : 'Mo\u017Enosti',
anchor_names : 'Sidra',
target_same : 'Odpri v tem oknu / okvirju',
target_parent : 'Odpri v nadrejenem oknu / okvirju',
target_top : 'Odpri v vrhnjem okvirju (nadomesti vse okvirje)',
target_blank : 'Odpri v novem oknu',
popup : 'Javascript pojavno okno',
popup_url : 'URL naslov pojavnega okna',
popup_name : 'Ime okna',
popup_return : 'Vstavi \'return false\'',
popup_scrollbars : 'Prika\u017Ei drsnike',
popup_statusbar : 'Prika\u017Ei vrstico stanja',
popup_toolbar : 'Prika\u017Ei orodjarno',
popup_menubar : 'Prika\u017Ei meni',
popup_location : 'Prika\u017Ei naslovno vrstico',
popup_resizable : 'Omogo\u010Di pove\u010Devanje okna',
popup_dependent : 'Odvisno (le za Mozillo/Firefox)',
popup_size : 'Velikost',
popup_position : 'Polo\u017Eaj (X/Y)',
id : 'Id',
style: 'Slog',
classes : 'Razredi',
target_name : 'Ime cilja',
langdir : 'Smer pisave',
target_langcode : 'Ciljni jezik',
langcode : 'Koda jezika',
encoding : 'Ciljno kodiranje znakov',
mime : 'Ciljni MIME tip',
rel : 'Razmerje strani do cilja',
rev : 'Razmerje cilja do strani',
tabindex : 'Zap. \u0161t.',
accesskey : 'Tipka dostopa',
ltr : 'Od leve proti desni',
rtl : 'Od desne proti levi'
});