// ES lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrita (Ctrl+B)',
italic_desc : 'Cursiva (Ctrl+I)',
underline_desc : 'Subrayado (Ctrl+U)',
striketrough_desc : 'Tachado',
justifyleft_desc : 'Alinear a la izquierda',
justifycenter_desc : 'Alinear al centro',
justifyright_desc : 'Alinear a la derecha',
justifyfull_desc : 'Justificar',
bullist_desc : 'Lista desordenada',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Reducir sangr&iacute;',
indent_desc : 'Aumentar  sangr&iacute;',
undo_desc : 'Deshacer (Ctrl+Z)',
redo_desc : 'Rehacer (Ctrl+Y)',
link_desc : 'Insertar/editar hiperv&iacute;nculo',
unlink_desc : 'Quitar hiperv&iacute;nculo',
image_desc : 'Insertar/editar imagen',
cleanup_desc : 'Limpiar c&oacute;digo basura',
focus_alert : 'El &aacute;rea del editor ha de ser seleccionada antes de ejecutar esta acci&oacute;n.',
edit_confirm : '¿Desea utilizar el modo WYSIWYG para esta caja de texto?',
insert_link_title : 'Insertar/editar hiperv&iacute;nculo',
insert : 'Insertar',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL del hiperv&iacute;nculo',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir v&iacute;nculo en la misma ventana',
insert_link_target_blank : 'Abrir v&iacute;nculo en una ventana nueva',
insert_image_title : 'Insertar/editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripci&oacute;n de la imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Pegar no se encuentra disponible en Mozilla y Firefox.\n ¿Desea obtener m&aacute;s informaci&oacute;n acerca de este tema?',
popup_blocked : 'Lo sentimos, su bloqueo de ventanas emergentes ha deshabilitado una ventana que provee funcionalidades a la aplicaci&oacute;n. Necesita deshabilitar este bloqueo en este sitio para poder utilizar todas las funciones.'
});
