// JA lang variables
// Translator Mitsuhiro Yoshida (http://mitstek.com/)

tinyMCE.addToLang('',{
bold_desc : '太字 (Ctrl+B)',
italic_desc : '斜体 (Ctrl+I)',
underline_desc : '下線 (Ctrl+U)',
striketrough_desc : '取り消し線',
justifyleft_desc : '左揃え',
justifycenter_desc : '中央揃え',
justifyright_desc : '右揃え',
justifyfull_desc : '均等割り付け',
bullist_desc : '箇条書き',
numlist_desc : '段落番号',
outdent_desc : 'インデント解除',
indent_desc : 'インデント',
undo_desc : '元に戻す (Ctrl+Z)',
redo_desc : 'やり直し (Ctrl+Y)',
link_desc : 'ハイパーリンクを挿入/編集する',
unlink_desc : 'ハイパーリンクを削除する',
image_desc : 'イメージを挿入/編集する',
cleanup_desc : 'コードの整理',
focus_alert : 'このコマンドを使用する場合、エディタにフォーカスする必要があります。',
edit_confirm : 'このテキストエリアで本当にWYSIWYGモードを使用しますか?',
insert_link_title : 'リンクを挿入/編集する',
insert : '挿入',
update : '更新',
cancel : 'キャンセル',
insert_link_url : 'リンクURI',
insert_link_target : 'ターゲット',
insert_link_target_same : 'リンクを同じウインドウで開く',
insert_link_target_blank : 'リンクを新しいウインドウで開く',
insert_image_title : 'イメージを挿入/編集する',
insert_image_src : 'イメージURI',
insert_image_alt : 'イメージ説明',
help_desc : 'ヘルプ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'MozillaおよびFirefoxでは、コピー/切り取り/貼り付けを使用することはできません。\nこの問題に関する詳細情報が必要ですか?',
popup_blocked : '申し訳ございません、あなたのポップアップブロッカーがエディタ機能を提供するウインドウを無効にしているようです。このツールを使用するには、ポップアップブロックを無効にする必要があります。'
});
