// SL lang variables

tinyMCE.addToLang('',{
bold_desc : 'Krepko (Ctrl+B)',
italic_desc : 'Le\u017Ee\u010De (Ctrl+I)',
underline_desc : 'Pod\u010Drtano (Ctrl+U)',
striketrough_desc : 'Pre\u010Drtano',
justifyleft_desc : 'Poravnaj levo',
justifycenter_desc : 'Na sredino',
justifyright_desc : 'Poravnaj desno',
justifyfull_desc : 'Porazdeli vsebino',
bullist_desc : 'Ozna\u010Devanje',
numlist_desc : 'O\u0161tevil\u010Devanje',
outdent_desc : 'Pove\u010Daj zamik',
indent_desc : 'Zmanj\u0161aj zamik',
undo_desc : 'Razveljavi (Ctrl+Z)',
redo_desc : 'Uveljavi (Ctrl+Y)',
link_desc : 'Vstavi/uredi povezavo',
unlink_desc : 'Odstrani povezavo',
image_desc : 'Vstavi/uredi sliko',
cleanup_desc : 'Pre\u010Disti kodo',
focus_alert : 'Urejevalnik mora biti izbran pred uporabo tega ukaza.',
edit_confirm : '\u017Delite uporabiti na\u010Din \'videz ne vara\' (WYSIWYG) za to vnosno polje?',
insert_link_title : 'Vstavi/uredi povezavo',
insert : 'Vstavi',
update : 'Posodobi',
cancel : 'Prekli\u010Di',
insert_link_url : 'URL povezave',
insert_link_target : 'Cilj',
insert_link_target_same : 'Odpri povezavo v istem oknu',
insert_link_target_blank : 'Odpri povezavo v novem oknu',
insert_image_title : 'Vstavi/uredi sliko',
insert_image_src : 'URL slike',
insert_image_alt : 'Opis slike',
help_desc : 'Pomo\u010D',
bold_img : 'bold_sl.gif',
italic_img : 'italic_sl.gif',
underline_img : 'underline_sl.gif',
clipboard_msg : 'Kopiraj/Izre\u017Ei/Prilepi v Mozilli in Firefoxu ni na voljo.\n\u017Delite ve\u010D informacij o tej te\u017Eavi?',
popup_blocked : '\u017Dal va\u0161e orodje za prepre\u010Devanje odpiranja neza\u017Eelenih oken (popup-blocker) ne omogo\u010Da prikaza pomo\u017Enega okna izbranega orodja. Prepre\u010Devanje odpiranja oken morate onemogo\u010Diti.'
});
