// Trad. Chinese lang variables
// Translator Andy Chan (http://www.cite.hku.hk/)

tinyMCE.addToLang('',{
bold_desc : '粗體 (Ctrl+B)',
italic_desc : '斜體 (Ctrl+I)',
underline_desc : '底線 (Ctrl+U)',
striketrough_desc : '刪除線',
justifyleft_desc : '靠左',
justifycenter_desc : '置中',
justifyright_desc : '靠右',
justifyfull_desc : '左右對齊',
bullist_desc : '符號式清單',
numlist_desc : '編號式清單',
outdent_desc : '文字向左縮排',
indent_desc : '文字向右縮排',
undo_desc : '復原 (Ctrl+Z)',
redo_desc : '取消復原 (Ctrl+Y)',
link_desc : '插入/編輯連結',
unlink_desc : '移除連結',
image_desc : '插入/編輯圖片',
cleanup_desc : '清理混亂的程式碼',
focus_alert : '在執行這個命令之前，編輯器必需要是使用中。',
edit_confirm : '你想在這個文字區塊用WYSIWYG模式嗎？',
insert_link_title : '插入/編輯連結',
insert : '插入',
update : '更新',
cancel : '取消',
insert_link_url : '連結網址',
insert_link_target : '目標',
insert_link_target_same : '在同一視窗打開連結',
insert_link_target_blank : '在同新視窗打開連結',
insert_image_title : '插入/編輯圖片',
insert_image_src : '圖片網址',
insert_image_alt : '圖片描述',
help_desc : '幫助',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '複製/剪下/貼上功能在Mozilla和Firefox中不能使用.\n你想知更多這問題的相關資料嗎?',
popup_blocked : '對不起，我們發現你的彈出視窗阻檔器(popup-blocker)已阻檔了一個提供程式功能的視窗。你需要在本網站停用彈出視窗阻檔才能完全運用本工具。'
});
