// ES lang variables

tinyMCE.addToLang('media',{
title : 'Insertar/editar medio embebido',
desc : 'Insertar/editar medio embebido',
general : 'General',
advanced : 'Avanzado',
file : 'Archivo/URL',
list : 'Lista',
size : 'Dimensiones',
preview : 'Vista previa',
constrain_proportions : 'Bloquear relaci&oacute;n de aspecto',
type : 'Tipo',
id : 'Id',
name : 'Nombre',
class_name : 'Clase',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Comienzo Autom&aacute;tico',
loop : 'Repetitivo',
menu : 'Mostrar men&uacute;',
quality : 'Calidad',
scale : 'Scale',
align : 'Alineaci&oacute;n',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Fondo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cach&eacute;',
hidden : 'Oculto',
controller : 'Controller',
kioskmode : 'Kiosk mode',
playeveryframe : 'Reproducir todo los frames',
targetcache : 'Target cache',
correction : 'Sin correci&oacute;n',
enablejavascript : 'Habilitar JavaScript',
starttime : 'Inicio',
endtime : 'Fin',
href : 'Href',
qtsrcchokespeed : 'Velocidad del obturador',
target : 'Target',
volume : 'Volumen',
autostart : 'Comienzo Autom&aacute;tico',
enabled : 'Hanilitado',
fullscreen : 'Pantalla completa',
invokeurls : 'Invocar URLs',
mute : 'Silencio',
stretchtofit : 'Estirar para ajustar',
windowlessvideo : 'V&iacute;deo sin ventana',
balance : 'Balance',
baseurl : 'URL Base',
captioningid : 'Id de los subt&iacute;tulos',
currentmarker : 'Marcador actual',
currentposition : 'Posici&oacute;n actual',
defaultframe : 'Frame predeterminado',
playcount : 'Contar reproducciones',
rate : 'Ratio',
uimode : 'Modo UI',
flash_options : 'Opciones Flash',
qt_options : 'Opciones Quicktime',
wmp_options : 'Opciones Windows media player',
rmp_options : 'Opciones Real media player',
shockwave_options : 'Opciones Shockwave',
autogotourl : 'Ir a URL autom&aacute;ticamente',
center : 'Centrado',
imagestatus : 'Estado de la imagen',
maintainaspect : 'Mantener aspecto',
nojava : 'Sin java',
prefetch : 'Preb&uacute;squeda',
shuffle : 'Aleatorio',
console : 'Consola',
numloop : 'N&uacute;m. repeticiones',
controls : 'Controles',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Forzar estilo',
swstretchhalign : 'Forzar H-Align',
swstretchvalign : 'Forzar V-Align',
sound : 'Sonido',
progress : 'Progreso',
qtsrc : 'QT Src',
qt_stream_warn : 'Los recursos rtsp de Streaming deber&iacute;an a&ntilde;adirse en el campo QT Src de la pesta&ntilde;a avanzada.\nAdem&aacute;s deber&iacute;a a&ntilde;adir una versi&oacute;n no Streaming en el campo Src.'
});
