// SL lang variables

tinyMCE.addToLang('media',{
title : 'Vstavi/Uredi multimedijsko vsebino',
desc : 'Vstavi/Uredi multimedijsko vsebino',
general : 'Splo\u0161no',
advanced : 'Napredno',
file : 'Datoteka/URL',
list : 'Seznam',
size : 'Dimenzije',
preview : 'Predogled',
constrain_proportions : 'Obdr\u017Ei razmerje',
type : 'Tip',
id : 'Id',
name : 'Ime',
class_name : 'Razred',
vspace : 'N-razmik',
hspace : 'V-razmik',
play : 'Samodejno predvajaj',
loop : 'V zanki',
menu : 'Prika\u017Ei meni',
quality : 'Kakovost',
scale : 'Pove\u010Dava',
align : 'Poravnava',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Ozadje',
base : 'Baza',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Predpomnjenje',
hidden : 'Skrito',
controller : 'Nadzorni element',
kioskmode : 'Na\u010Din \'kiosk\'',
playeveryframe : 'Predvajaj vsak okvir',
targetcache : 'Ciljno predpomnjenje',
correction : 'Brez popravkov',
enablejavascript : 'Omogo\u010Di JavaScript',
starttime : '\u010Cas za\u010Detka',
endtime : '\u010Cas konca',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Cilj',
volume : 'Glasnost',
autostart : 'Samodejno za\u010Dni',
enabled : 'Omogo\u010Deno',
fullscreen : 'Cel zaslon',
invokeurls : 'Naslovi URLje', // ?
mute : 'Uti\u0161aj', // ?
stretchtofit : 'Raz\u0161iri',
windowlessvideo : 'Video brez okna',
balance : 'Ravnovesje',
baseurl : 'Temeljni URL',
captioningid : 'Oznaka podnapisov',
currentmarker : 'Trenutna oznaka',
currentposition : 'Trenutni polo\u017Eaj',
defaultframe : 'Privzeti okvir',
playcount : '\u0160tevilo predvajanj',
rate : 'Ocena', // ?
uimode : 'Na\u010Din vmesnika',
flash_options : 'Mo\u017Enosti Flash',
qt_options : 'Mo\u017Enosti Quicktime',
wmp_options : 'Mo\u017Enosti Windows media player',
rmp_options : 'Mo\u017Enosti Real media player',
shockwave_options : 'Mo\u017Enosti Shockwave',
autogotourl : 'Samodejno na URL',
center : 'Sredina',
imagestatus : 'Stanje slike',
maintainaspect : 'Ohrani razmerje', // Zakleni razmerje
nojava : 'Brez Jave',
prefetch : 'Vnaprej\u0161nje nalaganje',
shuffle : 'Pome\u0161aj',
console : 'Konzola',
numloop : '\u0160t. zank',
controls : 'Nadzorni elementi',
scriptcallbacks : 'Klicani skript',
swstretchstyle : 'Slog raztegovanja',
swstretchhalign : 'Raztegni V-poravnano',
swstretchvalign : 'Raztegni N-poravnano',
sound : 'Zvok',
progress : 'Napredek',
qtsrc : 'QT Vir',
qt_stream_warn : 'Teko\u010De RTSP vire dodajte v polje QT Vir na zavihku Napredno.\nPrav tako dodajte tudi ne-teko\u010Do razli\u010Dico v polje Vir.',
align_top : 'Na vrh',
align_right : 'Na desno',
align_bottom : 'Na dno',
align_left : 'Na levo',
align_center : 'Na sredino',
align_top_left : 'Levo zgoraj',
align_top_right : 'Desno zgoraj',
align_bottom_left : 'Levo spodaj',
align_bottom_right : 'Desno spodaj'
});