<?php
// WARNING: DO NOT EDIT THIS FILE!
//
// It is automatically generated by debconf and will be overwritten
// everytime the mahara Debian package is upgraded.
//
// Your local customizations should go into /etc/mahara/config.php

$cfg->dbtype   = 'postgres8';
$cfg->dbhost   = 'localhost';
$cfg->dbport   = '';
$cfg->dbname   = 'mahara';
$cfg->dbuser   = 'mahara';
$cfg->dbpass   = '';
$cfg->wwwroot = 'http://localhost/mahara/';
$cfg->smtphosts = '';
$cfg->dataroot = '/var/lib/mahara';
?>
